language: perl

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

before_install:
  - sudo apt-get update -qq
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init

install:
  - cpanm --quiet --notest Module::Install::AuthorTests
  - cpanm --quiet --notest Module::Install::DOAPChangeSets
  - cpan-install --deps

notifications:
  irc: "irc://irc.perl.org/#perlrdf"

