language: perl

perl:
  - "5.30.0"
  - "5.22.4"
  - "5.20.3"
  - "5.18.4"
  - "5.16.3"
  - "5.14.4"

before_install:
  - sudo apt-get update -qq
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init

install:
  - cpanm --quiet --notest Module::Install::AuthorTests
  - cpanm --quiet --notest Module::Install::DOAPChangeSets
  - cpan-install --deps

notifications:
  irc: "irc://irc.perl.org/#perlrdf"

